# Generated by Django 2.0.4 on 2018-04-07 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('types', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactioncategory',
            options={'verbose_name_plural': 'Transaction categories'},
        ),
    ]
