# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-01 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('types', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='weekly_amount',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_frequency',
            field=models.CharField(choices=[('We', 'Weekly'), ('Mo', 'Monthly')], default='We', max_length=2),
        ),
    ]
