# Generated by Django 2.0.4 on 2018-04-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('types', '0003_auto_20180408_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='color_display',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
