version: '3.3'

services:
  db:
    image: postgres:latest
    volumes: 
      - pg_data:/var/lib/postgres/data
    env_file:
      - ./config/settings/.env
  web:
    build: .
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/budgetme
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./config/settings/.env
    links:
      - db:budgetme_pg
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local

volumes:
    pg_data:
