# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
