# Generated by Django 2.0.6 on 2018-07-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_scheduledtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtransaction',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
